
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author STUDENTS
 */
public class Donordetails extends javax.swing.JFrame {

    /**
     * Creates new form bloodgroup
     */
    public Donordetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_dname = new javax.swing.JTextField();
        combo_dgroup = new javax.swing.JComboBox<>();
        txt_dage = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_dadress = new javax.swing.JTextArea();
        txt_dphone = new javax.swing.JTextField();
        combo_dstate = new javax.swing.JComboBox<>();
        combo_dcity = new javax.swing.JComboBox<>();
        combo_dlyear = new javax.swing.JComboBox<>();
        jButton_dsubmit = new javax.swing.JButton();
        jButton_dcancel = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        combo_dsex = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        combo_dyear = new javax.swing.JComboBox<>();
        combo_dmonth = new javax.swing.JComboBox<>();
        combo_dday = new javax.swing.JComboBox<>();
        combo_dlmonth = new javax.swing.JComboBox<>();
        combo_dlday = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 600));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("DONOR NAME");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("BLOOD GROUP");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("AGE");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("SEX");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("ADDRESS");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("PHONE NUMBER");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("STATE");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("CITY");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("LAST BLOOD  DONATED DATE");

        txt_dname.setBackground(new java.awt.Color(255, 0, 0));
        txt_dname.setName("dname"); // NOI18N

        combo_dgroup.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        combo_dgroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));
        combo_dgroup.setName("dgroup"); // NOI18N

        txt_dage.setBackground(new java.awt.Color(255, 0, 0));
        txt_dage.setName("dage"); // NOI18N

        txt_dadress.setBackground(new java.awt.Color(255, 0, 0));
        txt_dadress.setColumns(20);
        txt_dadress.setRows(5);
        txt_dadress.setName("daddress"); // NOI18N
        jScrollPane1.setViewportView(txt_dadress);

        txt_dphone.setBackground(new java.awt.Color(255, 0, 0));
        txt_dphone.setName("dphone"); // NOI18N
        txt_dphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dphoneActionPerformed(evt);
            }
        });

        combo_dstate.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        combo_dstate.setForeground(new java.awt.Color(255, 0, 51));
        combo_dstate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KERALA", "KARNATAKA", "TAMILNADU", "MUMBAI", "DELHI" }));
        combo_dstate.setName("dstate"); // NOI18N
        combo_dstate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_dstateActionPerformed(evt);
            }
        });

        combo_dcity.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        combo_dcity.setForeground(new java.awt.Color(255, 51, 0));
        combo_dcity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "COCHI", "THRISSUR", "TRIVANDRUM", "CALICUT" }));
        combo_dcity.setName("dcity"); // NOI18N
        combo_dcity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_dcityActionPerformed(evt);
            }
        });

        combo_dlyear.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        combo_dlyear.setForeground(new java.awt.Color(255, 0, 0));
        combo_dlyear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2000", "2001", "2003", "2004", "2005" }));
        combo_dlyear.setName("dnbd"); // NOI18N
        combo_dlyear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_dlyearActionPerformed(evt);
            }
        });

        jButton_dsubmit.setBackground(new java.awt.Color(204, 204, 204));
        jButton_dsubmit.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        jButton_dsubmit.setText("submit");
        jButton_dsubmit.setName("dsubmit"); // NOI18N
        jButton_dsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_dsubmitActionPerformed(evt);
            }
        });

        jButton_dcancel.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        jButton_dcancel.setText("CANCEL");
        jButton_dcancel.setName("dcancel"); // NOI18N
        jButton_dcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_dcancelActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Engravers MT", 1, 48)); // NOI18N
        jLabel12.setText("DONOR DETAILS INSERTION");

        combo_dsex.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        combo_dsex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE" }));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("DOB");

        combo_dyear.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        combo_dyear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2017", "2018", "2018", "2020" }));
        combo_dyear.setName("dyear"); // NOI18N
        combo_dyear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_dyearActionPerformed(evt);
            }
        });

        combo_dmonth.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        combo_dmonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AGS", "SEP", "OCT", "NOV", "DEC" }));
        combo_dmonth.setName("dmonth"); // NOI18N
        combo_dmonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_dmonthActionPerformed(evt);
            }
        });

        combo_dday.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        combo_dday.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        combo_dday.setName("ddate"); // NOI18N
        combo_dday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_ddayActionPerformed(evt);
            }
        });

        combo_dlmonth.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        combo_dlmonth.setForeground(new java.awt.Color(255, 0, 0));
        combo_dlmonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));

        combo_dlday.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        combo_dlday.setForeground(new java.awt.Color(255, 0, 0));
        combo_dlday.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_dphone))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel5))
                                    .addComponent(jLabel1))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(combo_dgroup, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txt_dname)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(txt_dage, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel4)
                                                .addGap(18, 18, 18)
                                                .addComponent(combo_dsex, 0, 0, Short.MAX_VALUE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(jScrollPane1)))))
                        .addGap(46, 46, 46))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(40, 40, 40)
                        .addComponent(combo_dday, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(combo_dmonth, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(combo_dyear, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_dsubmit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_dcancel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(117, 117, 117))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(combo_dlday, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(65, 65, 65)
                                    .addComponent(combo_dlmonth, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(57, 57, 57)
                                    .addComponent(combo_dlyear, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel9))
                                    .addGap(40, 40, 40)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(combo_dcity, javax.swing.GroupLayout.Alignment.TRAILING, 0, 365, Short.MAX_VALUE)
                                        .addComponent(combo_dstate, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 981, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_dname, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(combo_dgroup, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addComponent(combo_dlday, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(combo_dlmonth, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(combo_dlyear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txt_dage, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(combo_dstate, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addComponent(combo_dsex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_dphone, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(combo_dcity, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_dsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_dcancel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(combo_dday, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(combo_dmonth, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(combo_dyear, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combo_dstateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_dstateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_dstateActionPerformed

    private void combo_dyearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_dyearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_dyearActionPerformed

    private void combo_dmonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_dmonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_dmonthActionPerformed

    private void jButton_dcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_dcancelActionPerformed
this.setVisible (false);
              Mainmenu s=new Mainmenu();
              s.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_dcancelActionPerformed

    private void jButton_dsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_dsubmitActionPerformed

     String name=txt_dname.getText();
     String bg=combo_dgroup.getSelectedItem().toString();
     String age=txt_dage.getText();
     String sex=combo_dsex.getSelectedItem().toString();
     String addr=txt_dadress.getText();
     String phone=txt_dphone.getText(); 
     String nbd=combo_dlyear.getSelectedItem().toString();
     String date=combo_dday.getSelectedItem().toString()+"/"+combo_dmonth.getSelectedItem().toString()+"/"+combo_dyear.getSelectedItem().toString();
      String ldate=combo_dlday.getSelectedItem().toString()+"/"+combo_dlmonth.getSelectedItem().toString()+"/"+combo_dlyear.getSelectedItem().toString();
     String state=combo_dstate.getSelectedItem().toString();
     String city=combo_dcity.getSelectedItem().toString();
        try {
            Connection connect=DriverManager.getConnection("jdbc:mysql://localhost:3306/blood_db","root","");
            Statement stmt;
         stmt = connect.createStatement();
         
     String query =("insert into donor_details set dname='"+name+"',dgroup='"+bg+"',dage='"+age+"',dsex='"+sex+"',daddress='"+addr+"',dphone='"+phone+"',dldate='"+ldate+"',ddate='"+date+"',dstate='"+state+"',dcity='"+city+"'");
     
      System.out.println("hello");
     stmt.executeUpdate(query);
        System.out.println(query);
     //name = '"+name+"',email = '"+email+"',phone = '"+phone+"'");
            // TODO add your handling code here:
 JOptionPane.showMessageDialog(null,"DETAILS ARE SUCESSFULLY REGISTERD");
        } catch (SQLException ex) {
           // Logger.getLogger(bloodgroup.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_dsubmitActionPerformed

    private void txt_dphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dphoneActionPerformed

    private void combo_dcityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_dcityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_dcityActionPerformed

    private void combo_ddayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_ddayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_ddayActionPerformed

    private void combo_dlyearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_dlyearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_dlyearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Donordetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Donordetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Donordetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Donordetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Donordetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo_dcity;
    private javax.swing.JComboBox<String> combo_dday;
    private javax.swing.JComboBox<String> combo_dgroup;
    private javax.swing.JComboBox<String> combo_dlday;
    private javax.swing.JComboBox<String> combo_dlmonth;
    private javax.swing.JComboBox<String> combo_dlyear;
    private javax.swing.JComboBox<String> combo_dmonth;
    private javax.swing.JComboBox<String> combo_dsex;
    private javax.swing.JComboBox<String> combo_dstate;
    private javax.swing.JComboBox<String> combo_dyear;
    private javax.swing.JButton jButton_dcancel;
    private javax.swing.JButton jButton_dsubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txt_dadress;
    private javax.swing.JTextField txt_dage;
    private javax.swing.JTextField txt_dname;
    private javax.swing.JTextField txt_dphone;
    // End of variables declaration//GEN-END:variables
}
